config/routes.rb
Rails.application.routes.draw do

  root to: "stories#index"

  resources :stories, only: %w[ index show edit update ] do
    member do
      get :clicked
    end
  end
  resources :story_authors, only: %w[ index edit update destroy ]

  controller :static do
    get  "/contact", action: "contact", as: "contact"
    post "/contact", action: "contact"
    get  "/ping",    action: "ping", as: "ping"
  end

  # errors
  %w[
    catch_all not_found bad_request internal_server_error unprocessable_entity
    catch_all_test internal_server_error_test unprocessable_entity_test
  ].each do |action_name|
    get "/errors/#{action_name}", to: "errors##{action_name}"
  end
  post "/errors/internal_server_error_test", to: "errors#internal_server_error_test"


end

app/views/layouts/_flash.html.erb
<%
  alerts = {
    notice: :success,
    info: :info,
    warn: :warning,
    alert: :danger,
  }.with_indifferent_access
%>

<%= cp.div_tag(id: "flash-messages") do %>
  <% flash.each do |key, messages| %>
    <% messages = Array(messages).select(&:present?) %>
    <%= cp.alert_div(alerts.fetch(key), add_class: "flash-message") do %>
      <%= cp.dismiss_action(:alert) %>
      <% messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= cp.html_tag(:html, lang: "en") do %>
  <%= cp.html_tag(:head) do %>
    <!-- title -->
    <%= cp.html_tag(:title, content: Rails.application.settings.title) %>
    <!-- meta -->
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="version" content="<%= Rails.application.settings.version %>">
    <!-- opengraph -->
    <meta property="og:title" content="<%= Rails.application.settings.title %>"/>
    <meta property="og:url" content="http://<%= Rails.application.settings.domain %>"/>
    <meta property="og:site_name" content="<%= Rails.application.settings.title %>"/>
    <meta property="og:type" content="website"/>
    <meta property="og:image" content="http://<%= Rails.application.settings.domain %>/favicon.png"/>
    <meta property="og:description" content="Worm story search"/>
    <!-- touch icons by realfavicongenerator.net -->
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">
    <!-- stylesheet -->
    <%= stylesheet_link_tag("application", media: "all") %>
    <%= cp.style_tag(type: "text/css") do %>
      <% if get_theme == "dark" %>
        <%= render(partial: "layouts/dark_theme", formats: :scss) %>
      <% end %>      
    <% end %>
    <%= cp.style_tag(type: "text/css", media: "(prefers-color-scheme: dark)") do %>
      <% if get_theme == "auto" %>
        <%= render(partial: "layouts/dark_theme", formats: :scss) %>
      <% end %>
    <% end %>

    <!-- javascript -->
    <%= javascript_include_tag("application") %>
  <% end %>

  <%= cp.html_tag(:body, class: "#{controller_name} #{controller_name}-#{action_name}") do %>
    <%= cp.div_tag(class: "wrapper") do %>
      <%= cp.html_tag(:header) do %>
        <!-- navigation -->
        <%= cp.html_tag(:nav, class: "navbar navbar-inverse navbar-static-top", style: "padding-left: 0px; padding-right: 0px;") do %>
          <%= cp.container_div do %>
            <!-- left brand -->
            <%= cp.link_to(root_url, class: "navbar-brand") do %>
              <%= cp.span_tag(class: "hidden-xs hidden-sm", content: Rails.application.settings.title) %>
              <%= cp.span_tag(class: "visible-xs visible-sm", content: "Stories") %>
            <% end %>

            <% if get_theme == "light" %>
              <%= cp.link_to(root_url(theme: "dark"), class: "navbar-brand pull-right") do %>
                <%= cp.span_tag(content: "Dark") %>
              <% end %>
            <% elsif get_theme == "dark" %>
              <%= cp.link_to(root_url(theme: "auto"), class: "navbar-brand pull-right") do %>
                <%= cp.span_tag(content: "Auto") %>
              <% end %>
            <% else %>
              <%= cp.link_to(root_url(theme: "light"), class: "navbar-brand pull-right") do %>
                <%= cp.span_tag(content: "Light") %>
              <% end %>
            <% end %>

            <% if Rails.env.development? %>
              <% Rails.application.settings.request_count ||= 0 %>
              <% request_count = Rails.application.settings.request_count += 1 %>
              <%= cp.p_tag(class: "navbar-text", style: "margin-left: 5px; margin-right: 5px; display: inline-block;") do %>
                <%= cp.label_span(request_count == 1 ? "success" : "info", content: "Request: #{request_count}") %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>

      <!-- main content -->
      <%= cp.container_div do %>
        <!-- flash -->
        <%= cp.row_div(id: "flash") do %>
          <%= cp.col_div(col_sm: 12) do %>
            <%= render partial: "layouts/flash" %>
          <% end %>
        <% end %>

        <!-- content -->
        <%= cp.row_div(id: "content") do %>
          <%= cp.col_div(col_sm: 12) do %>
            <%= yield %>
          <% end %>
        <% end %>

        <!-- hidden content -->
        <%= cp.div_tag(style: "" || "display: none;") do %>
          <%= render_partial(:dynamic_modal) %>
        <% end %>
      <% end %>

      <!-- footer -->
      <%= cp.container_div do %>
        <%= cp.html_tag(:footer) do %>
          <%= cp.row_div(id: "footer") do %>
            <%= cp.col_div(col_sm: 12) do %>
              <%= cp.hr_tag %>
              NOTE: FanFiction.net updates are not working due to new bot restrictions they implemented.
              <%= cp.br_tag %>
              Thank you wormverse community authors for all the great stories!
              <%= cp.br_tag %>
              <%= cp.small_tag do %>
                Click <%= cp.link_to(contact_path, content: "here") %> to provide feedback, suggestions, and bug reports.
                Code on <%= cp.link_to("https://github.com/griffithchaffee/wormstorysearch-rails", content: "Github - v#{Rails.application.settings.version}") %>.
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/modal.html.erb
<%= cp.div_tag(class: "modal") do %>
  <%= cp.div_tag(class: "modal-header") do %>
    <%= cp.dismiss_action(:modal) %>
    <%= cp.h4_tag(class: "modal-title") do %>
      <%= yield(:title) %>
    <% end %>
  <% end %>

  <%= cp.div_tag(class: "modal-body") do %>
    <%= render_partial("layouts/flash") %>
    <%= yield %>
  <% end %>


  <%= cp.div_tag(class: "modal-footer") do %>
    <% if content_for?(:footer) %>
      <%= yield(:footer) %>
    <% else %>
      <%= cp.modal_close_btn %>
    <% end %>
  <% end %>
<% end %>